name: 'coco_dbt_demo'
version: '1.0.0'

profile: 'coco_dbt_demo'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  coco_dbt_demo:
    staging:
      +materialized: view
      +schema: ANALYTICS
    marts:
      +materialized: table
      +schema: ANALYTICS
